### ISSUE TITLE
IP address Encrypted

### ISSUE THREAD

**Issue by tboulogne** [georgemarshall/django-cryptography#19]
Hello,

I face this issue
```
django.db.utils.ProgrammingError: cannot cast type inet to bytea
LINE 1: ...access" ALTER COLUMN "ac_ip" TYPE bytea USING "ac_ip"::bytea
```
When i try to encrypt an ipaddress field :
```
ac_ip = encrypt(models.GenericIPAddressField(
        verbose_name="IP", protocol='IPv4', blank=True, null=True))
```

Anyway to workaround this ?

Thanks for your help.

Regards,

Thierry

**Comment by thismatters** [comment]
Sorry for the delayed response, I hope you found a workaround to this! For any who encountering this problem for the first time... This seems like another one of those issues that can be fixed by making a _new_ encrypted field, migrating the data to it, then deleting the old plaintext field, finally rename the new encrypted field to whatever the old field was named. It is the standard switcheroo required when encrypting a field.

**Comment by georgemarshall** [comment]
Information about encrypting a field can be found in https://github.com/georgemarshall/django-cryptography/issues/11
