### ISSUE TITLE
Q Query

### ISSUE THREAD

**Issue by Bastilla123** [georgemarshall/django-cryptography#20]
I have following model:

class Adressen(models.Model):
    geburtsdatum = encrypt(models.DateField(default=None,blank=True,null=True))

views:
    start = date.today()
    end = start + timedelta(days=14)
    Geburtstage = Adressen.objects.filter(
        Q(geburtsdatum__month=start.month) & Q(geburtsdatum__day__gte=start.day) |
        Q(geburtsdatum__month=end.month) & Q(geburtsdatum__day__lte=end.day)
    ).order_by('geburtsdatum')

Exception:

django.core.exceptions.FieldError: Unsupported lookup 'month' for EncryptedDateField or join on the field not permitted, perhaps you meant month?

**Comment by thismatters** [comment]
Encrypted fields generally don't support lookup within querysets since the data in the actual table cannot be compared to what it is required to match. The only way to do what you are trying to do would be to query for _all_ of the `Adressen` objects and iterate over them until you find the one whose attributes match.
