### ISSUE TITLE
Handling of SALT

### ISSUE THREAD

**Issue by Gee19** [georgemarshall/django-cryptography#25]
Upon first glance it looks like this library is using a default hardcoded SALT for every encrypted field. 

https://github.com/georgemarshall/django-cryptography/blob/master/django_cryptography/conf.py#L13

Am I misunderstanding something or can you point me in the right direction where a unique salt is generated for each new field?

**Comment by georgemarshall** [comment]
The `SALT` has to be consistent in order to generate the same decryption key. It is an exercise left to the user to change the value.

Additional information can be found in the [cryptography library docs](https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/#cryptography.hazmat.primitives.kdf.pbkdf2.PBKDF2HMAC).
